services:
  noc-server:
    build: .
    container_name: noc-server
    restart: unless-stopped
    ports:
      - "3066:3066"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run dev

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-noc
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiMTNjZTc1MDJmYmEzNTcyMzJkN2YxOTg1YWI4MGUwYzIiLCJ0IjoiNGZhNzk3NjItZWMxOS00MTY0LWIzNmUtYjc1MTdhZjFhNzQ3IiwicyI6Ik5UZGxaV05oTVdNdE5HWmlOeTAwWlRJMkxUbGpZamd0TldZME1ESTJPVFJqTUdNeCJ9
    depends_on:
      - noc-server

    